const keysNames = ['Backquote', 'Digit1', 'Digit2', 'Digit3', 'Digit4', 'Digit5', 'Digit6', 'Digit7', 'Digit8', 'Digit9', 'Digit0', 'Minus', 'Equal',
  'KeyQ', 'KeyW', 'KeyE', 'KeyR', 'KeyT', 'KeyY', 'KeyU', 'KeyI', 'KeyO', 'KeyP', 'BracketLeft', 'BracketRight', 'Backslash',
  'KeyA', 'KeyS', 'KeyD', 'KeyF', 'KeyG', 'KeyH', 'KeyJ', 'KeyK', 'KeyL', 'Semicolon', 'Quote', 'Enter',
  'KeyZ', 'KeyX', 'KeyC', 'KeyV', 'KeyB', 'KeyN', 'KeyM', 'Comma', 'Period', 'Slash', 'Space']

const letters = ['ё', '1', '2', '3', '4', '5', '6', '7', '8', '9', '0', '-', '=', 'BackSpace',
  'Tab', 'й', 'ц', 'у', 'к', 'е', 'н', 'г', 'ш', 'щ', 'з', 'х', 'ъ', 'Slash',
  'CapsLock', 'ф', 'ы', 'в', 'а', 'п', 'р', 'о', 'л', 'д', 'ж', 'э', 'Enter',
  'я', 'ч', 'с', 'м', 'и', 'т', 'ь', 'б', 'ю', '.', 'Slash', 'Up',
  'Ctrl', 'Win', 'Alt', 'Space', 'Alt', 'Left', 'Bottom', 'Right', 'Ctrl']

const CharCodes = [1105, 49, 50, 51, 52, 53, 54, 55, 56, 57, 48, 45, 61,
  1081, 1094, 1091, 1082, 1077, 1085, 1075, 1096, 1097, 1079, 1093, 1098, 92,
  1092, 1099, 1074, 1072, 1087, 1088, 1086, 1083, 1076, 1078, 1101, 13,
  1103, 1095, 1089, 1084, 1080, 1090, 1100, 1073, 1102, 46,
  32]


const keys = [
  {
    code: 'Backquote',
    ru: 'ё',
    ruShift: 'Ё',
    ruCaps: 'Ё',
    ruShiftCaps: 'ё',
    en: '`',
    enShift: '~',
    enCaps: '`',
    enShiftCaps: '~',
  },
  {
    code: 'Digit1',
    ru: '1',
    ruShift: '!',
    ruCaps: '1',
    ruShiftCaps: '!',
    en: '1',
    enShift: '!',
    enCaps: '1',
    enShiftCaps: '!',
  },
  {
    code: 'Digit2',
    ru: '2',
    ruShift: '"',
    ruCaps: '2',
    ruShiftCaps: '"',
    en: '2',
    enShift: '@',
    enCaps: '2',
    enShiftCaps: '@',
  },
  {
    code: 'Digit3',
    ru: '3',
    ruShift: '№',
    ruCaps: '3',
    ruShiftCaps: '№',
    en: '3',
    enShift: '#',
    enCaps: '3',
    enShiftCaps: '#',
  },
  {
    code: 'Digit4',
    ru: '4',
    ruShift: ';',
    ruCaps: '4',
    ruShiftCaps: ';',
    en: '4',
    enShift: '$',
    enCaps: '4',
    enShiftCaps: '$',
  },
  {
    code: 'Digit5',
    ru: '5',
    ruShift: '%',
    ruCaps: '5',
    ruShiftCaps: '%',
    en: '5',
    enShift: '%',
    enCaps: '5',
    enShiftCaps: '%',
  },
  {
    code: 'Digit6',
    ru: '6',
    ruShift: ':',
    ruCaps: '6',
    ruShiftCaps: ':',
    en: '6',
    enShift: '^',
    enCaps: '6',
    enShiftCaps: '^',
  },
  {
    code: 'Digit7',
    ru: '7',
    ruShift: '?',
    ruCaps: '7',
    ruShiftCaps: '?',
    en: '7',
    enShift: '&',
    enCaps: '7',
    enShiftCaps: '&',
  },
  {
    code: 'Digit8',
    ru: '8',
    ruShift: '*',
    ruCaps: '8',
    ruShiftCaps: '*',
    en: '8',
    enShift: '*',
    enCaps: '8',
    enShiftCaps: '*',
  },
  {
    code: 'Digit9',
    ru: '9',
    ruShift: '(',
    ruCaps: '9',
    ruShiftCaps: '(',
    en: '9',
    enShift: '(',
    enCaps: '9',
    enShiftCaps: '(',
  },
  {
    code: 'Digit0',
    ru: '0',
    ruShift: ')',
    ruCaps: '0',
    ruShiftCaps: ')',
    en: '0',
    enShift: ')',
    enCaps: '0',
    enShiftCaps: ')',
  },
  {
    code: 'Minus',
    ru: '-',
    ruShift: '_',
    ruCaps: '-',
    ruShiftCaps: '_',
    en: '-',
    enShift: '_',
    enCaps: '-',
    enShiftCaps: '_',
  },
  {
    code: 'Equal',
    ru: '=',
    ruShift: '+',
    ruCaps: '=',
    ruShiftCaps: '+',
    en: '=',
    enShift: '+',
    enCaps: '=',
    enShiftCaps: '+',
  },
  {
    code: 'Backspace',
    ru: 'Backspace',
    ruShift: 'Backspace',
    ruCaps: 'Backspace',
    ruShiftCaps: 'Backspace',
    en: 'Backspace',
    enShift: 'Backspace',
    enCaps: 'Backspace',
    enShiftCaps: 'Backspace',
  },
  {
    code: 'Tab',
    ru: 'Tab',
    ruShift: 'Tab',
    ruCaps: 'Tab',
    ruShiftCaps: 'Tab',
    en: 'Tab',
    enShift: 'Tab',
    enCaps: 'Tab',
    enShiftCaps: 'Tab',
  },
  {
    code: 'KeyQ',
    ru: 'й',
    ruShift: 'Й',
    ruCaps: 'Й',
    ruShiftCaps: 'й',
    en: 'q',
    enShift: 'Q',
    enCaps: 'Q',
    enShiftCaps: 'q',
  },
  {
    code: 'KeyW',
    ru: 'ц',
    ruShift: 'Ц',
    ruCaps: 'Ц',
    ruShiftCaps: 'ц',
    en: 'w',
    enShift: 'W',
    enCaps: 'W',
    enShiftCaps: 'w',
  },
  {
    code: 'KeyE',
    ru: 'у',
    ruShift: 'У',
    ruCaps: 'У',
    ruShiftCaps: 'у',
    en: 'e',
    enShift: 'E',
    enCaps: 'E',
    enShiftCaps: 'e',
  },
  {
    code: 'KeyR',
    ru: 'к',
    ruShift: 'К',
    ruCaps: 'К',
    ruShiftCaps: 'к',
    en: 'r',
    enShift: 'R',
    enCaps: 'R',
    enShiftCaps: 'r',
  },
  {
    code: 'KeyT',
    ru: 'е',
    ruShift: 'Е',
    ruCaps: 'Е',
    ruShiftCaps: 'е',
    en: 't',
    enShift: 'T',
    enCaps: 'T',
    enShiftCaps: 't',
  },
  {
    code: 'KeyY',
    ru: 'н',
    ruShift: 'Н',
    ruCaps: 'Н',
    ruShiftCaps: 'н',
    en: 'y',
    enShift: 'Y',
    enCaps: 'Y',
    enShiftCaps: 'y',
  },
  {
    code: 'KeyU',
    ru: 'г',
    ruShift: 'Г',
    ruCaps: 'Г',
    ruShiftCaps: 'г',
    en: 'u',
    enShift: 'U',
    enCaps: 'U',
    enShiftCaps: 'u',
  },
  {
    code: 'KeyI',
    ru: 'ш',
    ruShift: 'Ш',
    ruCaps: 'Ш',
    ruShiftCaps: 'ш',
    en: 'i',
    enShift: 'I',
    enCaps: 'I',
    enShiftCaps: 'i',
  },
  {
    code: 'KeyO',
    ru: 'щ',
    ruShift: 'Щ',
    ruCaps: 'Щ',
    ruShiftCaps: 'щ',
    en: 'o',
    enShift: 'O',
    enCaps: 'O',
    enShiftCaps: 'o',
  },
  {
    code: 'KeyP',
    ru: 'з',
    ruShift: 'З',
    ruCaps: 'З',
    ruShiftCaps: 'з',
    en: 'p',
    enShift: 'P',
    enCaps: 'P',
    enShiftCaps: 'p',
  },
  {
    code: 'BracketLeft',
    ru: 'х',
    ruShift: 'Х',
    ruCaps: 'Х',
    ruShiftCaps: 'х',
    en: '[',
    enShift: '{',
    enCaps: '[',
    enShiftCaps: '{',
  },
  {
    code: 'BracketRight',
    ru: 'ъ',
    ruShift: 'Ъ',
    ruCaps: 'Ъ',
    ruShiftCaps: 'ъ',
    en: ']',
    enShift: '}',
    enCaps: ']',
    enShiftCaps: '}',
  },
  {
    code: 'Backslash',
    ru: '/',
    ruShift: '/',
    ruCaps: '/',
    ruShiftCaps: '/',
    en: '/',
    enShift: '|',
    enCaps: '/',
    enShiftCaps: '|',
  },
  {
    code: 'Delete',
    ru: 'Delete',
    ruShift: 'Delete',
    ruCaps: 'Delete',
    ruShiftCaps: 'Delete',
    en: 'Delete',
    enShift: 'Delete',
    enCaps: 'Delete',
    enShiftCaps: 'Delete',
  },
  {
    code: 'CapsLock',
    ru: 'CapsLock',
    ruShift: 'CapsLock',
    ruCaps: 'CapsLock',
    ruShiftCaps: 'CapsLock',
    en: 'CapsLock',
    enShift: 'CapsLock',
    enCaps: 'CapsLock',
    enShiftCaps: 'CapsLock',
  },
  {
    code: 'KeyA',
    ru: 'ф',
    ruShift: 'Ф',
    ruCaps: 'Ф',
    ruShiftCaps: 'ф',
    en: 'a',
    enShift: 'A',
    enCaps: 'A',
    enShiftCaps: 'a',
  },
  {
    code: 'KeyS',
    ru: 'ы',
    ruShift: 'Ы',
    ruCaps: 'Ы',
    ruShiftCaps: 'ы',
    en: 's',
    enShift: 'S',
    enCaps: 'S',
    enShiftCaps: 's',
  },
  {
    code: 'KeyD',
    ru: 'в',
    ruShift: 'В',
    ruCaps: 'В',
    ruShiftCaps: 'в',
    en: 'd',
    enShift: 'D',
    enCaps: 'D',
    enShiftCaps: 'd',
  },
  {
    code: 'KeyF',
    ru: 'а',
    ruShift: 'А',
    ruCaps: 'А',
    ruShiftCaps: 'а',
    en: 'f',
    enShift: 'F',
    enCaps: 'F',
    enShiftCaps: 'f',
  },
  {
    code: 'KeyG',
    ru: 'п',
    ruShift: 'П',
    ruCaps: 'П',
    ruShiftCaps: 'п',
    en: 'g',
    enShift: 'G',
    enCaps: 'G',
    enShiftCaps: 'g',
  },
  {
    code: 'KeyH',
    ru: 'р',
    ruShift: 'Р',
    ruCaps: 'Р',
    ruShiftCaps: 'р',
    en: 'h',
    enShift: 'H',
    enCaps: 'H',
    enShiftCaps: 'h',
  },
  {
    code: 'KeyJ',
    ru: 'о',
    ruShift: 'О',
    ruCaps: 'О',
    ruShiftCaps: 'о',
    en: 'j',
    enShift: 'J',
    enCaps: 'J',
    enShiftCaps: 'j',
  },
  {
    code: 'KeyK',
    ru: 'л',
    ruShift: 'Л',
    ruCaps: 'Л',
    ruShiftCaps: 'л',
    en: 'k',
    enShift: 'K',
    enCaps: 'K',
    enShiftCaps: 'k',
  },
  {
    code: 'KeyL',
    ru: 'д',
    ruShift: 'Д',
    ruCaps: 'Д',
    ruShiftCaps: 'д',
    en: 'l',
    enShift: 'L',
    enCaps: 'L',
    enShiftCaps: 'l',
  },
  {
    code: 'Semicolon',
    ru: 'ж',
    ruShift: 'Ж',
    ruCaps: 'Ж',
    ruShiftCaps: 'ж',
    en: ';',
    enShift: ':',
    enCaps: ';',
    enShiftCaps: ':',
  },
  {
    code: 'Quote',
    ru: 'э',
    ruShift: 'Э',
    ruCaps: 'Э',
    ruShiftCaps: 'э',
    en: '"',
    enShift: '"',
    enCaps: '"',
    enShiftCaps: '"',
  },
  {
    code: 'Enter',
    ru: 'Enter',
    ruShift: 'Enter',
    ruCaps: 'Enter',
    ruShiftCaps: 'Enter',
    en: 'Enter',
    enShift: 'Enter',
    enCaps: 'Enter',
    enShiftCaps: 'Enter',
  },
  {
    code: 'ShiftLeft',
    ru: 'Shift',
    ruShift: 'Shift',
    ruCaps: 'Shift',
    ruShiftCaps: 'Shift',
    en: 'Shift',
    enShift: 'Shift',
    enCaps: 'Shift',
    enShiftCaps: 'Shift',
  },
  {
    code: 'KeyZ',
    ru: 'я',
    ruShift: 'Я',
    ruCaps: 'Я',
    ruShiftCaps: 'я',
    en: 'z',
    enShift: 'Z',
    enCaps: 'Z',
    enShiftCaps: 'z',
  },
  {
    code: 'KeyX',
    ru: 'ч',
    ruShift: 'Ч',
    ruCaps: 'Ч',
    ruShiftCaps: 'ч',
    en: 'x',
    enShift: 'X',
    enCaps: 'X',
    enShiftCaps: 'x',
  },
  {
    code: 'KeyC',
    ru: 'с',
    ruShift: 'С',
    ruCaps: 'С',
    ruShiftCaps: 'с',
    en: 'c',
    enShift: 'C',
    enCaps: 'C',
    enShiftCaps: 'c',
  },
  {
    code: 'KeyV',
    ru: 'м',
    ruShift: 'М',
    ruCaps: 'М',
    ruShiftCaps: 'м',
    en: 'v',
    enShift: 'V',
    enCaps: 'V',
    enShiftCaps: 'v',
  },
  {
    code: 'KeyB',
    ru: 'и',
    ruShift: 'И',
    ruCaps: 'И',
    ruShiftCaps: 'и',
    en: 'b',
    enShift: 'B',
    enCaps: 'B',
    enShiftCaps: 'b',
  },
  {
    code: 'KeyN',
    ru: 'т',
    ruShift: 'Т',
    ruCaps: 'Т',
    ruShiftCaps: 'т',
    en: 'n',
    enShift: 'N',
    enCaps: 'N',
    enShiftCaps: 'n',
  },
  {
    code: 'KeyM',
    ru: 'ь',
    ruShift: 'Ь',
    ruCaps: 'Ь',
    ruShiftCaps: 'ь',
    en: 'm',
    enShift: 'M',
    enCaps: 'M',
    enShiftCaps: 'm',
  },
  {
    code: 'Comma',
    ru: 'б',
    ruShift: 'Б',
    ruCaps: 'Б',
    ruShiftCaps: 'б',
    en: ',',
    enShift: '<',
    enCaps: ',',
    enShiftCaps: '<',
  },
  {
    code: 'Period',
    ru: 'ю',
    ruShift: 'Ю',
    ruCaps: 'Ю',
    ruShiftCaps: 'ю',
    en: '.',
    enShift: '>',
    enCaps: '.',
    enShiftCaps: '>',
  },
  {
    code: 'Slash',
    ru: '.',
    ruShift: ',',
    ruCaps: '.',
    ruShiftCaps: ',',
    en: '/',
    enShift: '?',
    enCaps: '/',
    enShiftCaps: '?',
  },
  {
    code: 'ArrowUp',
    ru: '▲',
    ruShift: '▲',
    ruCaps: '▲',
    ruShiftCaps: '▲',
    en: '▲',
    enShift: '▲',
    enCaps: '▲',
    enShiftCaps: '▲',
  },
  {
    code: 'ShiftRight',
    ru: 'Shift',
    ruShift: 'Shift',
    ruCaps: 'Shift',
    ruShiftCaps: 'Shift',
    en: 'Shift',
    enShift: 'Shift',
    enCaps: 'Shift',
    enShiftCaps: 'Shift',
  },
  {
    code: 'ControlLeft',
    ru: 'Ctrl',
    ruShift: 'Ctrl',
    ruCaps: 'Ctrl',
    ruShiftCaps: 'Ctrl',
    en: 'Ctrl',
    enShift: 'Ctrl',
    enCaps: 'Ctrl',
    enShiftCaps: 'Ctrl',
  },
  {
    code: 'MetaLeft',
    ru: 'Win',
    ruShift: 'Win',
    ruCaps: 'Win',
    ruShiftCaps: 'Win',
    en: 'Win',
    enShift: 'Win',
    enCaps: 'Win',
    enShiftCaps: 'Win',
  },
  {
    code: 'AltLeft',
    ru: 'Alt',
    ruShift: 'Alt',
    ruCaps: 'Alt',
    ruShiftCaps: 'Alt',
    en: 'Alt',
    enShift: 'Alt',
    enCaps: 'Alt',
    enShiftCaps: 'Alt',
  },
  {
    code: 'Space',
    ru: '',
    ruShift: '',
    ruCaps: '',
    ruShiftCaps: '',
    en: '',
    enShift: '',
    enCaps: '',
    enShiftCaps: '',
  },
  {
    code: 'AltRight',
    ru: 'Alt',
    ruShift: 'Alt',
    ruCaps: 'Alt',
    ruShiftCaps: 'Alt',
    en: 'Alt',
    enShift: 'Alt',
    enCaps: 'Alt',
    enShiftCaps: 'Alt',
  },
  {
    code: 'ArrowLeft',
    ru: '◄',
    ruShift: '◄',
    ruCaps: '◄',
    ruShiftCaps: '◄',
    en: '◄',
    enShift: '◄',
    enCaps: '◄',
    enShiftCaps: '◄',
  },
  {
    code: 'ArrowDown',
    ru: '▼',
    ruShift: '▼',
    ruCaps: '▼',
    ruShiftCaps: '▼',
    en: '▼',
    enShift: '▼',
    enCaps: '▼',
    enShiftCaps: '▼',
  },
  {
    code: 'ArrowRight',
    ru: '►',
    ruShift: '►',
    ruCaps: '►',
    ruShiftCaps: '►',
    en: '►',
    enShift: '►',
    enCaps: '►',
    enShiftCaps: '►',
  },
  {
    code: 'ControlRight',
    ru: 'Ctrl',
    ruShift: 'Ctrl',
    ruCaps: 'Ctrl',
    ruShiftCaps: 'Ctrl',
    en: 'Ctrl',
    enShift: 'Ctrl',
    enCaps: 'Ctrl',
    enShiftCaps: 'Ctrl'
  }
]

export default keys;